{{- if or ( .Values.serviceAccount.create ) ( .Values.cloudsqlproxy.workloadIdentity.enabled ) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-mysql-exporter.serviceAccountName" . }}
  labels:
    app: {{ template "prometheus-mysql-exporter.name" . }}
    chart: {{ template "prometheus-mysql-exporter.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.cloudsqlproxy.workloadIdentity.enabled }}
  annotations:
  {{- with .Values.serviceAccount.annotations  }}
      {{- toYaml . | nindent 4 }}
  {{- end }}
    {{ template "prometheus-mysql-exporter.workloadIdentityAnnotation" . }}
  {{- else }}
  {{- with .Values.serviceAccount.annotations  }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end -}}
